name: Continuous Integration/ Continuous Deployment
on:
  pull_request_target:
    types:
      - closed
    branches: [dev]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: adding aws credentials
      run: sed -i 's|"access_key_id"|"${{secrets.ACCESS_KEY}}"|g;s|"secret_key_id"|"${{secrets.SECRET_KEY}}"|g' dev_index.js
      shell: bash

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./dev.Dockerfile
        push: true
        tags: tibildocker/spec_ms:dev

    - name: Docker pull image and deploy from hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.DEV_HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        PORT: '22'
        script: |
          docker login
          docker pull tibildocker/spec_ms
          docker stop ansible_spec_app_1 || true
          docker rm ansible_spec_app_1 || true
          docker rmi tibildocker/spec_ms:dev || true
          docker run -d --name ansible_spec_app_1 -p 3001:3001 --network ansible_cqube_net tibildocker/spec_ms:dev
